name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: sudo su
      - run: npm i parcel
      - run: rm -rf dist
      - run: npm run build
      - run: cd /var/www/dev-malviyalokesh.live/
      - run: rm -rf html/*
      - run: cd /home/ubuntu/actions-runner-ui-server/_work/react_server/react_server
      - run: sudo cp -a dist/. /var/www/dev-malviyalokesh.live/html/
